### ISSUE TITLE
“Список проектов”: уточнить обязательность заполнения поля "Описание"

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#112]

**Comment by vliplianina** [comment]
Требование относится не к списку проектов, а к форме создания проекта.
На форме создания проекта поле не обязательно для заполнения.

Обновлено в [требованиях](https://github.com/vliplianina/team2b/blob/master/TrainingTask%20-%20Requirements.md) п.5 "Форма ввода проекта"
