### ISSUE TITLE
 Добавление задачи: невозможно добавить несколько сотрудников на 1 задачу

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#147]
Важность: **critical**
Шаги:

Перейти в раздел "Задачи"
Нажать кнопку "Добавить"
Перейти к полю "Исполнитель"
Результат:
Возможно выбрать только 1 исполнителя

Ожидаемый результат:
Есть возможность выбрать нескольких исполнителей (см. Функциональные требования [п.3](https://github.com/vliplianina/team2b/blob/master/TrainingTask%20-%20Requirements.md))

**Comment by vliplianina** [comment]
Принято.

Замечание:
1) шаги должны быть пронумерованы.
2) следует добавить отступ между шагами и полученным результатом
