### ISSUE TITLE
"Список проектов": При удалении проекта, прикрепленные к нему задачи удаляются

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#149]
Важность: critical
**Предусловие:**

1)В списке проектов есть как минимум 1 запись
2)В списке задач есть минимум 1 запись, прикрепленная к проекту из п.1

**Шаги:**

Перейти в раздел "Список проектов"
Нажать кнопку "Удалить" проект

Результат:
Проект удаляется и все прикрепленные к нему задачи так же удаляются

Ожидаемый результат:
Проект удаляется, но все прикрепленные к нему задачи остаются со значением полем "Проект" пустым.

**Comment by vliplianina** [comment]
Принято.
