### ISSUE TITLE
Форма “Список проектов”: уточнить сценарий приложения при успешном добавлении проекта.

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#28]
Необходимо уточнить как ведет себя приложение при успешном добавлении проекта. 
Появляется ли сообщение для пользователя об успешном добавлении проекта?

**Comment by vliplianina** [comment]
При заполнении полей на форме создания проекта допустимыми данными и нажатии кнопки "Сохранить", проект сохраняется, осуществляется переход на форму со списком проектов.
Сообщение не появляется.

Примечание: поведение относится к реализации формы создания проекта, а не ко списку проектов.
