### ISSUE TITLE
Форма “Список проектов”: уточнить поля колонок:  Идентификатор, Название, Сокращенное название, Описание

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#4]
Необходимо  уточнить **формат ввода данных**, **физические ограничения**, **обязательность заполнения** для колонок:  Идентификатор, Название, Сокращенное название, Описание.

**Comment by vliplianina** [comment]
Что именно требуется уточнить? Перечень полей?

**Comment by alisa98** [comment]
Да, необходимо уточнить перечень полей.

**Comment by vliplianina** [comment]
Заголовок и описание содержат разную информацию. Возможно, было исправлено после уточняющего вопроса.
Согласно требованиям, в списке проектов должны быть следующие колонки: 
* Идентификатор, 
* Название, 
* Сокращенное название, 
* Описание.

Вопрос о формате ввода данных и обязательности заполнения некорректен, т.к. изменять данные прямо в таблице нельзя. Максимальное физ.ограничение соответствует максимальному кол-ву символов, установленному на форме создания проекта.
