### ISSUE TITLE
Форма ввода персоны (исполнителя): определить алфавит и/или возможные символы для ввода в поля "Фамилия", "Имя", "Отчество"

### ISSUE THREAD

**Issue by katerinachikova** [vliplianina/team2b#5]
Русские, английские буквы
Допустимость ввода цифр, специальных символов, многих знаков пробела подряд и тп

**Comment by vliplianina** [comment]
Допустимые алфавиты: латиница и кириллица  
Символы: буквы, пробел, спец.символы -.' (дефис, точка, кавычка)

**Comment by vliplianina** [comment]
Добавлено в требования п. 7. Форма ввода персоны (исполнителя)
