### ISSUE TITLE
“Список проектов”: уточнить физические и логические ограничения поля "Описание"

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#69]

**Comment by vliplianina** [comment]
В списке проектов должны отображаться значения, которые можно сохранить на форме ввода проекта. 

На форме ввода проекта:
не обязательно для заполнения, допустимые символы [A-z],[А-я], [0-9] пробел, [-.,':;?!"?$()], максимум 1000 символов
Обновлено в [требованиях](https://github.com/vliplianina/team2b/blob/master/TrainingTask%20-%20Requirements.md) п.5 "Форма ввода проекта"
