### ISSUE TITLE
“Список проектов”: уточнить как осуществляется действие “Изменить”  

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#72]
Необходимо уточнить как осуществляется действие “Изменить” . 
Например: необходимо кликнуть правой кнопкой мыши по нужному проекту в таблице, после чего выпадает список с полем "изменить" .

**Comment by vliplianina** [comment]
Действие осуществляется по нажатию на кнопку "Изменить".
По нажатию на кнопку "Изменить" происходит переход к форме редактирования соответствующего проекта.
