### ISSUE TITLE
“Список проектов”: уточнить запрашивает ли приложения подтверждение на удаление проекта

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#77]
Необходимо уточнить запрашивает ли приложения подтверждение на удаление проекта. Выводит ли форму с сообщение, например, "Удалить проект?" и кнопками "Да", "Нет"?

**Comment by vliplianina** [comment]
Дублирование уточнения из запроса #76 
Подтверждающее сообщение не реализовано.
