### ISSUE TITLE
“Список проектов”: уточнить сценарий приложения , если количество записей в таблице превышает видимую область страницы

### ISSUE THREAD

**Issue by alisa98** [vliplianina/team2b#81]

**Comment by vliplianina** [comment]
См. коммантарий к запросу #34

**Comment by alisa98** [comment]
Ссылка на запрос [#34](https://github.com/vliplianina/team2b/issues/34) введет на уточнение не связанное с темой.
Имелось в виду: осуществляется скрол или пагинация страниц?

**Comment by vliplianina** [comment]
Комментарий добавлен ошибочно. Должен появляться скролл.
